var KeyMirror = require('keymirror')

const AssetErrorCodes = KeyMirror({
  INTERNAL_SERVER_ERROR: null,
  EMAIL_REQUIRED: null,
  ADDRESS_REQUIRED: null,

  TELEPHONE_REQUIRED: null,
  TELEPHONE_INVALID: null,

  CITIZEN_ID_REQUIRED: null,
  CITIZEN_ID_INVALID: null,

  USER_ID_REQUIRED: null,
  USER_ID_INVALID: null,
  USER_NOT_FOUND: null,

  PRODUCT_ID_REQUIRED: null,
  PRODUCT_ID_INVALID: null,
  PRODUCT_NOT_EXISTS: null,
  PRODUCT_NAME_REQUIRED: null,
  PRODUCT_PRICE_REQUIRED: null,
  PRODUCT_UNIT_REQUIRED: null,
  PRODUCT_IMAGE_REQUIRED: null,
  PRODUCT_IMAGE_FORBIDEN: null,
  PRODUCT_URL_REQUIRED: null,
  PRODUCT_URL_FORBIDEN: null,

  PACK_ID_REQUIRED: null,
  PACK_ID_INVALID: null,
  PACK_ID_NOT_EXISTS: null,
  PACK_NAME_REQUIRED: null,

  LOCATION_ID_REQUIRED: null,
  LOCATION_ID_INVALID: null,
  LOCATION_NOT_EXISTS: null,
})

module.exports = {AssetErrorCodes}
